### PR TITLE
Preview in Ubuntu

### PR DESCRIPTION
**Pull request by dirtydancing**
As discussed in https://github.com/numixproject/numix-folders/issues/13 here are the preview screenshots of the Numix Folders Styles 1 to 6 in Ubuntu.

### CODE REVIEW

**Comment by Foggalong** [comment]
That's brilliant :D Can you move the images into [this directory](https://github.com/numixproject/numix-folders/tree/master/files/1) for each style so it's alongside the preview and then rename to `screenshot.png`. Then amend README.md so that it follows this pattern

```markdown
| Style | Preview  | Screenshot | Description |
| :------------: |:---------------:|:-----:|:-----:|
| **0** | - | - | The default in our base theme - choose this to revert back |
| **1** | ![1](https://raw.githubusercontent.com/numixproject/numix-folders/master/files/1/preview.png) | ![1](https://raw.githubusercontent.com/numixproject/numix-folders/master/files/1/screenshot.png) | The original folder design |
```
Then should be able to merge in :D

**Comment by dirtydancing** [comment]
Ok, I guess I am in need of a little help here :-), please forgive my ignorance, this is my very first pull request, and I am not quite sure what is happening here? Have I already modified my pull request here by changing the repository that I created by forking from this repository?

Anyways, I am running into difficulties with the README.md. The problem appears to be that the screenshot graphic is displayed in full size in the folder style table, which is 1280x800 and thus way too large.

Example screenshot:

example

So I experimented with thumbnails and links (I changed the screenshot image link to my repository for testing purposes in order to be able to view the screenshots), but did not really get anywhere. I am not sure if there is a simple way to limit the size of the table/column, so that the screenshot.png is not displayed in full size in the README overview, but only once the screenshot is actually clicked.

What do you make of this?

**Comment by Foggalong** [comment]
Oh shoot, pasted you the wrong mardown code -_-* really sorry!

**Comment by Foggalong** [comment]
Congratulations on your first pull request!

**Comment by dirtydancing** [comment]
Thanks! And no worries about the "wrong" markdown code: this way, at least my testing was of relevance :-) I will put in the new code right away.

I figure I will be getting get more proficient with GitHub/git along the way; for the time being, I am simply going along with your useful guide to contributing over at Ozon OS: https://github.com/ozonos/ozon-icon-theme/wiki/Contributing

**Comment by dirtydancing** [comment]
Almost getting there! Here is a screenshot of the updated version with the new code (apparently, the links to the screenshot files still have to be adjusted to numixproject, but of course they are not in the numixproject repo yet, so the screenshots would not show in my repo).

styles_screenshot_link

One suggestion: Is it possible to have the screenshots open in a new browser window? This would make sense, because the folder icon preview opens up in a new window as well (and also other screenshots I have clicked on in GitHub), and this also useful if s.o. would like to look at different screenshots next to each other in different windows.

**Comment by dirtydancing** [comment]
This e.g. seems to work (opening in new window), going from markdown to plain html:
`<a href="https://raw.githubusercontent.com/dirtydancing/numix-folders/master/files/1/screenshot.png" target="_blank">link</a>`
instead of
`[link](https://raw.githubusercontent.com/dirtydancing/numix-folders/master/files/1/screenshot.png)`

**Comment by dirtydancing** [comment]
Just experimented with the spontaneous idea to add a `:camera:` emoji for "screenshot", and this would also be working in combination with the plain text "link".

But to me it looks like adding an image would not add any functionality and actually distract from the folder icon previews, so I would recommend to simply keep the plain text "link" without any images.

Screenshots:

camera_1

camera_2

**Comment by Foggalong** [comment]
Yeah, camera is a neat idea but as you say a bit distracting. Stick with "[link](http://ddg.gg/)". Also, please keep the `[link](https://url.png)` format for URLs. It means that people can open the readme in desktop readers that support markdown, and people can always open in a new tab if they need to compare.

**Comment by dirtydancing** [comment]
Ah, I see, the markdown support makes sense (and just to clarify: when I was writing "new window" I meant "new tab").

I realised that in markdown the exclamation point is referring to an image, and I figure that is why when the preview folder icons are clicked, the image opens in a new tab (just like screenshot images in conversations open in a new tab). In contrast, without the exclamation mark it is a link (not an image), and apparently by default links are opened in the same tab. I just got confused because in this case, the "link" refers to a screenshot image :-)

Finalising this now.

**Comment by dirtydancing** [comment]
Ok, with latest commit 90d1694, the preview in Ubuntu screenshots should now be ready to be merged.

**Comment by Foggalong** [comment]
You're a star! Thanks for doing this :D

**Comment by dirtydancing** [comment]
My pleasure :-)

**Pull request merged**
