### PR TITLE
Use all the colours you can store in 24bit 

### PR DESCRIPTION
**Pull request by wa4557**
I was always a little bit disappointed that the folder-switch only has its predefined colors. So i fiddled a little bit with the script, and now it's possible to use any color combinations you want (even really ugly ones). I have no idea if this is something you want to happen since it's probably better to somehow dictate the design, but nevertheless, here's what I came up with. 

I created a new "color" called "custom" which is rather an svg file which has three strings in it "replacecolour1" "replacecolour2" and "replacecolour3" that are replaced with colours the user can choose beforehand after copying the files to the Numix folder.

I think this is a rather elegant approach, and it works pretty well. As you can see I've chosen some random colour to demonstrate it
unbenannt

### CODE REVIEW

**Comment by dirtydancing** [comment]
Please also cf. https://github.com/numixproject/numix-folders/issues/65 concerning the "custom" colour option in Folder Color.

@wa4557 does this script also cover e.g. style 5, which has more than 3 colours?

**Comment by dirtydancing** [comment]
Or maybe it does not have more than 3 colours, I am actually not sure about that :)

**Comment by wa4557** [comment]
To make it short: yes you can change all three colours. You can actually try it, it works already pretty good

**Comment by Foggalong** [comment]
Can we split [this line](https://github.com/wa4557/numix-folders/blob/custom/numix-folders#L109) and [this line](https://github.com/wa4557/numix-folders/blob/custom/numix-folders#L127) up a bit? If at some point we end up adding more colours then they're going to get a bit unwieldy.

**Comment by wa4557** [comment]
Here we go

**Comment by dirtydancing** [comment]
Thanks for clarifying, got the colouring of the folder icons now :).

One more suggestion: as this pull request is also modifying the Readme (custom - - -) , and as the colour values gain more importance if the user can customise, I think it would now make sense to specify the default colour values for the 6 folder styles as well, probably in a separate chart below the "Colours" chart. E.g. this would also allow to specify the white symbol colour `#fff8e1` for style 5, which does not appear on the current colour chart. Should I open a separate issue for that? Actually, I will do so, to avoid cluttering. That issue can just be closed if not needed.

colours

**Comment by wa4557** [comment]
Ok unnecessary tab deleted :) One more thing: is it possible that the colours in the readme are wrong? The symbol colors are for most of the styles different, than what's in the readme

**Comment by dirtydancing** [comment]
As to the colours in the current colour chart: it seems to me that the symbol colour values reflect what is actually displayed on screen, even if in Inkscape the colour is different, which might be due to opacity.

**Comment by Foggalong** [comment]
Yeah, the colours in the symbol column reflect the actual colour of the symbol rather than the colour Inkscape uses.

**Comment by dirtydancing** [comment]
This might be a completely stupid question, but if it is possible to simply specify the different global folder colours (with all the shadows e.g. in style 5 and such, and with the action icons as well) by changing the hex values, why then have different icons for the different colours at all? Would that be exclusively for the individual folder colour changes via Folder Color? Otherwise, maybe the script could be adapted to automatically select hex values for the three colours if e.g. "blue" or, for that matter s.th. like "brown-old-default" is entered? Just wondering :)

**Comment by Foggalong** [comment]
Yeah, the default colours have to be already made up as oppose to being created on the fly so that Folder Color can be supported.

**Comment by Foggalong** [comment]
@wa4557 @dirtydancing I can test this right now, but am I right in thinking that this implementation will break if the user trys to use the "custom" option more than once?

**Comment by dirtydancing** [comment]
Can't test right now, but I can come back to this.

**Comment by wa4557** [comment]
No it won't because all the files are copied beforehand `cp -rf styles/"${style}"/Numix/* "${dir}"/Numix/` and only afterwards the colors are changed but not in the `numix-folder` folder but in `"${dir}"/Numix/` therefore you can do it as often as you want

**Comment by dirtydancing** [comment]
OK, I have given the script a test run. It does not break even after a couple of "custom"-runs.

But I have come across some difficulties:

1) I was confused by the naming of the three colours as main colour, dark background colour, darker background colour. I think this could be adapted to the naming in the Readme chart: primary colour, secondary colour, symbol colour (if that is what is represented).

2) For some reason, the second colour did not show. I always ended up with the first colour only.

3) The third (symbol) colour did not show as entered, maybe because there is some opacity involved?

4) For style 5, the third colour did not colour theme the symbol, which looked consistently white.

5) For style 2, I ended up with the third colour being displayed as main folder colour.

Just some first findings. The good news: I could come back to the default settings without a problem :)

**Comment by dirtydancing** [comment]
I think this might be a problem with the custom folders rather than with the script? I only checked briefly. Can you reproduce this? I believe this is a very promising approach, and I would like to see this work.

**Comment by Foggalong** [comment]
RE 3: Yeah, symbols work using opacity so they'll always look lighter than the colour that's inputed by the user.

**Comment by wa4557** [comment]
Hi, 

1) Ok will change that. 
2) Cannot reproduce that, works for me, are you sure?
3) Yeah not much I can do about that, I could try to translate that but that may be hard to do 
4) Yeah I will change that
5) No idea why this happens, but I will try and change that

**Comment by Foggalong** [comment]
It'd be impossible within the scope of this script because it's dependent on the colour behind it.

**Comment by wa4557** [comment]
4) I'm not sure I should change that. I mean for all the other colours the symbol stays the same for style 5

**Comment by wa4557** [comment]
1 & 2 is fixed, 3 and probably 4 is a wontfix. 5 happens because of a bug in numix-folder I'll wait until this one is merged to fix that

**Comment by dirtydancing** [comment]
4) Can be argued either way indeed. For the already existing folder colors, in style 5 the symbol is always the same white (apparently no decreased opacity for the symbol in style 5). On the other hand, to give the user maximum flexibility with the colours, it would make sense to be able to choose a darker symbol colour for a lighter main colour. Given the choice, I think I would prefer to be able to choose the symbol colour, esp. when the option is already given in the script, and works for the other styles.

**Comment by dirtydancing** [comment]
Of course, that white symbol colour value for style 5 should be listed in the Readme somewhere :)

**Comment by wa4557** [comment]
Nah I won't change that right now, because that would mean that I have to do the same thing for 1 and 2 and 5. Moreover to keep it consistent it shouldn't be changeable...
Ok I tested now everything and everything seems to be in place

**Comment by dirtydancing** [comment]
Sounds good! As you wrote "to keep it consistent": do I understand it correctly that the symbol colour is not changeable in any style? In the styles with a dark symbol the colour (in Inkscape) also stays the same for all folder colours so far?

**Comment by wa4557** [comment]
It's changeable for style 3, 4 and 6 just like for the other colors

**Comment by dirtydancing** [comment]
But does it really change for the other colours in style 3, 4 and 6? Or are the different colours on the screen merely a result of the same symbol colour with opacity, which then is displayed differently on screen because the main folder colour has changed?

**Comment by wa4557** [comment]
Definitely; brown for example has #241714 blue #072a5eff

**Comment by dirtydancing** [comment]
Yeah, there are different symbol colours with opacity for those styles, I was just wondering.

**Comment by dirtydancing** [comment]
Some more testing results: This is already running much better, nice! Some further aspects below.

Haha, just to give you an impression, here is a screenshot of my testing, in this case with style 6 :)

custom

0) btw, this screenshot and the screenshot below also show that (imo) it still would make sense to be able to change the symbol colour for e.g. style 5, as the currently fixed white will not work ideally with lighter main folder colours. For your consideration :)

custom2

1) Two colours are showing for style 5, white for symbol is staying. Maybe to clarify, for those styles with currently fixed symbol colour this should be mentioned in the Readme.

2) Style 2 now picks up the primary colour correctly, but does not pick up the secondary colour. That is probably because there is no secondary colour :), but then again this might be confusing for the users.

3) Style 2 does not seem to pick up the symbol colour. Probably also a fixed symbol colour here, although not white, which also might be confusing for the users.

4) Correspondingly, style 1 is only picking up the primary colour. This and also 1) and 2) and 3) leads to another idea: is it possible to only display the colour options for each style that actually can be changed? E.g. for style 1, only display the primary colour option, and not the secondary and the symbol colour options.

1-4) Summing up, this leads to the suggestion to adapt the selection of custom colour choices to the respective folder style.

This would also make sense to stay open for folder design with more than 3 colours: if there were e.g. 5 colour choices, it would be unfortunate to be given 5 colour choices e.g. for style 1, which currently only has 1 primary colour choice. And currently, apparently the user has to fill in every colour choice given to make this work, even if that colour is not present in the folder style at all (?).

5) Extra idea/question: would it be possible/sensible also for the custom colour option (like for style and colour) to automatically enter the "default" colour value when only return is pressed (again adapted to the folder style chosen, just like the selection of primary/secondary/symbol)? Could make sense e.g. if a user of a default style colouring does not want to change all the colours, but only one specific colour. Might be too complicated, just an idea.

**Comment by wa4557** [comment]
1) if the symbol colour cannot be changed it doesn't have to be mentioned in the Readme. I agree however that the fact that it's confusing that there's still the choice to change it in the script. I will change that
2) Style two and one do not have secondary colours
3) The symbol in style 2 is pitch black with less opacity. So shouldn't be changeable 
4) Same here. I will change the script accordingly
5) Maybe. I'll look into that

**Comment by dirtydancing** [comment]
Great! Just to clarify about 0) (not being able to change the symbol colour for styles 1, 2 and 5): Is the reason for this that this feature is difficult to implement, or is the reason that the symbol colour for these three styles is "dictated"?

I am asking because if this global/default custom colour option is let loose on the users, you might probably prepare to see some very "individual" colour choices. So when the cat is out of the bag anyways, so to say, there seems to be no reason to hold back on those select symbol colours. It is an inconsistency as well, because you can change the symbol colour in styles 3, 4 and 6.

Sorry for asking again, I just happen to be a fan of style 5, and this is one of the styles in which currently the symbol colour can not be changed :)

**Comment by dirtydancing** [comment]
One more thought in support of having the symbol colour changeable consistently: Let's say a user prefers one folder shape and additionally another default folder colour: Currently, it should be possible to replicate the default colours of e.g. style 5 in a style 6 custom folder, but not the other way around.

**Comment by dirtydancing** [comment]
I have been wondering about another thing: why do the symbol colours for several folder styles use a reduced opacity? Would it make sense to have the colours in the Readme list also in Inkscape with 100% opacity (if easy enough to change)? That way, also the symbol colour would actually be the colour that the user enters (relating to the custom colour script) (?).

**Comment by wa4557** [comment]
Yeah I was thinking about this as well and I think it would make sense. However right now I have now idea how to do this automatically, and I will certainly not go through all the styles and sizes and do this by hand :) Default values are fixed now btw.

**Comment by dirtydancing** [comment]
Great, I will give the new script version a go a little later then. And yeah, changing thousands of folder icon files one by one is probably not the way to go :)

**Comment by wa4557** [comment]
Ok it is now possible to change symbol colour for all styles + default values + opacity problem is also by using non opaque colours. I tried to tested it and it worked great.
@dirtydancing If you fancy to test this as well I would be very grateful

**Comment by dirtydancing** [comment]
Wow, this is fantastic! The first thing I did is replicate the colours of style 2 in style 5 (with three different colours), because iirc the colours in style 2 have been/are popular ones with the user base. Worked :):

custom_1

On to style 1 with the colours of style 5:

custom_2

1) Something seems to be off with the default colour names for style 1. In addition, now for style 1 only two colour choices are given, which is good. But while the first colour was correctly named primary colour, the second colour was named secondary colour, but should rather be named symbol colour, if possible, to make things as clear as possible. Furthermore, apparently the symbol colour for style 1 did not get changed.

Style 4 with folder colour `#ff0000`, so opacity problem looks solved:

custom_3

Hitting enter with all three colours in style 4 leads to this, so default seems to work:

custom_4

Just entering some random values for styles 6 and 3, whatever :):

custom_5

custom_6

Same for style 2, and in contrast to style 1, primary and symbol colour were shown and worked:

custom_7

This is how far I got for the time being. No breakage so far, fun stuff, and of course useful as well :)

**Comment by wa4557** [comment]
The symbol colur in style 1 cannot be changed because the symbols are not coloured but rather cut out from the base plate -> this will not change :)
Colour two is used for style 1 for a few icons. So everything ok there

**Comment by dirtydancing** [comment]
Ah, ok. So for style 1: maybe point the user to what the secondary colour is about? This will likely lead to confusion, because users will assume that the secondary colour is for the symbol in the folder (?).

**Comment by dirtydancing** [comment]
Folder Color for individual folders works as well. Worked for individual folder colouring after the global colour had been set via script, and then I changed the global colour again via the script, and the individual colours were still showing:

custom_8

Still working also when setting everything back to default via enter key with the script:

custom_9

**Comment by wa4557** [comment]
Well that's why it says primary and secondary colour and not symbol colour :P

**Comment by dirtydancing** [comment]
Problem when going down to size 16x16 in Nautilus: the folders in the custom default colour are not shown in size 16x16, but rather scaled down (only seems to occur with size 16x16 and seems to be ok with the default plain folder without a symbol):

custom_10

**Comment by dirtydancing** [comment]
A to style 1: well, normally the "secondary colour" is used for the same folder in combination with the primary colour in all other styles that have a secondary colour, so "secondary colour" in style 1 is still not clear. It confused me, and I can almost guarantee that it will confuse others as well :)

**Comment by wa4557** [comment]
Ok 16x16 is fixed. I think that this is ready to merge!? This also fixes #7 kind of

**Comment by dirtydancing** [comment]
Confirmed that 16x16 is fixed and now uses the primary colour (btw I like the aspect that the default colour value is displayed for each colour that can be customized):

custom_11

I would still recommend to adjust the "secondary colour" situation in style 1. Where is this used? Is this an inconsistency in the folder colouring that should be addressed there, so that there can be just one "primary colour" to customize?

**Comment by wa4557** [comment]
Yeah it seems to me that this is an inconsistency. Those are the files that use a different color instead of shading in style 1 (for all colours of course). If and when that is fixed I can fix the custom folders in style 1 as well. Until then this PR should not be fixed

./64x64/places/custom-fileopen.svg
./64x64/places/custom-folder-open.svg
./64x64/actions/custom-document-open-recent.svg
./64x64/actions/custom-add-folders-to-archive.svg
./64x64/actions/custom-document-open.svg
./32x32/places/custom-fileopen.svg
./32x32/actions/custom-document-open-recent.svg
./32x32/actions/custom-add-folders-to-archive.svg
./32x32/actions/custom-document-open.svg
./256x256/actions/custom-add-folders-to-archive.svg
./96x96/places/custom-fileopen.svg
./96x96/actions/custom-document-open-recent.svg
./96x96/actions/custom-add-folders-to-archive.svg
./96x96/actions/custom-document-open.svg
./22x22/places/custom-fileopen.svg
./22x22/actions/custom-document-open-recent.svg
./22x22/actions/custom-add-folders-to-archive.svg
./22x22/actions/custom-document-open.svg
./24x24/places/custom-fileopen.svg
./24x24/actions/custom-document-open-recent.svg
./24x24/actions/custom-add-folders-to-archive.svg
./24x24/actions/custom-document-open.svg
./48x48/places/custom-fileopen.svg
./48x48/actions/custom-document-open-recent.svg
./48x48/actions/custom-add-folders-to-archive.svg
./48x48/actions/custom-document-open.svg
./16x16/places/custom-fileopen.svg
./16x16/actions/custom-document-open-recent.svg
./16x16/actions/custom-add-folders-to-archive.svg
./16x16/actions/custom-document-open.svg
./128x128/places/custom-fileopen.svg
./128x128/places/custom-folder-open.svg
./128x128/actions/custom-document-open-recent.svg
./128x128/actions/custom-add-folders-to-archive.svg
./128x128/actions/custom-document-open.svg

**Comment by dirtydancing** [comment]
Yeah, this seems to be a wrong colouring as well, because apparently currently the colour in the background that should be somewhat darker actually is lighter?

Actually, as these are only a few icons per colour and as these seem to be only small sections of the entire icon, and in order to keep these issues and fixes separate, in this case I would recommend to not give an option in the script for the "secondary colour" in style 1 at all and simply leave it as it is until fixed.

Is it possible to add a shading of the primary for the custom colour icons at least, so that those could be addressed fully with only one primary colour?

**Comment by dirtydancing** [comment]
I figure that the script should not be catering to a "bug" in the folder design itself. If a user chooses two entirely different colours for primary and secondary (as I did when testing) and then only sees the primary colour and in exceptional cases a touch of a completely different secondary colour, this does not really help either :)

**Comment by wa4557** [comment]
Yeah true, but I have actually no idea how to fix that

**Comment by wa4557** [comment]
Could you open a issue for that? I'm wondering what the design actual design should look like (additional second colour or 40% opaque primary colour for the background). I guess you're better than me in creating those issue reports:)

**Comment by dirtydancing** [comment]
How is this handled in style 2?

**Comment by dirtydancing** [comment]
Ah, that is apparently the "symbol colour" in style 2 that also comprises the borders of the icon.

**Comment by wa4557** [comment]
No. There's a shadow overlay that makes the back a tad darker

**Comment by dirtydancing** [comment]
I see. So I guess this should be handled in a similar fashion for style 1.

How to deal with this in this PR? Is it doable to just use one colour until this is fixed for the folder design and then add such a shadow overlay to the custom colour icons as well? Alternatively, I would suggest to just keep the present default colour un-customisable for the time being (?).

One more thing is: if a user starts off experimenting with the script with style 1 (like I happened to do), the "secondary colour" choice in the script for style 1 could lead to a confusing and discouraging start.

**Comment by dirtydancing** [comment]
Just filing the corresponding issue report. How about `folder-move` in `places`, Is that also handled with a second colour in style 1?

**Comment by wa4557** [comment]
Depends. I think the better way would be to use always the same colour in style 1 and just work with black shadows / more opacity. But yes this one should be consistent with all the other icons in the list

**Comment by dirtydancing** [comment]
How does `folder-open` in `places` in your list above use two different colours? Looks like that one is using less opacity for the lighter part, but just one colour.

**Comment by wa4557** [comment]
Yeah but it's not. The back one is indeed 100% opacity just a lighter colour

**Comment by dirtydancing** [comment]
Strange. So that is a third colour for all the non-default colours then? Because there then appears to be a darker and a lighter colour when compared to the primary colour for style 1 in those icons.

**Comment by wa4557** [comment]
No I was wrong. It's the secondary colour with 66% opacity

**Comment by dirtydancing** [comment]
Even stranger. Why use a secondary colour with opacity for that, when also the primary colour with opacity could be used? Is the secondary colour also used for the darker part of that icon, so that the primary colour does not appear at all?

**Comment by wa4557** [comment]
No :)

**Comment by dirtydancing** [comment]
Issue report filed, https://github.com/numixproject/numix-folders/issues/68, we will see what will come of this :)

**Comment by dirtydancing** [comment]
1) Style 1: in the latest version of the script, only one primary colour choice is left. Good! it looks like the "secondary" color now is black no matter which primary color is chosen? This looks a lot darker than in the predefined colours, cf. screenshots. Is this a workaround until e.g. a shadow overlay is defined?

recent_1a
recent_1b

2) Question concerning style 2: is the "border" around the folders the symbol colour, or is it the primary colour with a shadow overlay? Currently, in the custom colour folders, it is the symbol colour:

custom_style2
recent_2

3) Something went wrong when I hit enter for the folder style (to get the default style) and then entered "custom" as folder colour: no hex value choices were given, but the folders turned to black (going back to the defaults by hitting enter twice after that was no problem, though; also entering "6" for style and then "custom" for colour worked just fine):

enter_custom

4) When entering the colour values, the letters can be in upper case as well as in lower case. But for "custom", only "custom" works, not "Custom". This might be separate enhancement that also has already come up for the colour names. E.g., "blue" is the standard spelling in lower case that also is listed in the Readme, cf. https://github.com/numixproject/numix-folders/pull/53, but it would be even better if "Blue" with "B" in upper case would work as well (or even "BLUE"?). This should be consistent for all the entries, so I am mentioning it here as well. This might already have changed in the master branch (did not check), although looking at the commit titles this has not been the case so far.

5) In continuation of 4): the master branch currently is 4 commits ahead of this branch/pull request. Does this have any impact on the issues that have come up here so far? Just a question.

**Comment by dirtydancing** [comment]
Addition to 3) above: the same issue appears (no choice of colour values, folders turn black) when "0" is entered for style and then "custom" for colour. The Readme states "0 - The default in our base theme - choose this to revert back". Works with entering a predefined colour afterwards, though, e.g. "blue".

**Comment by wa4557** [comment]
1) Yes this is a workaround, I can't do anything if I don't know how this will turn out
2) Yeah this is the symbol colour. But this is the designed behaviour, and I the script won't change the design so this will stay
3 & 4) Ok I will change that
5) no problem here

**Comment by wa4557** [comment]
Ok style 0 added + since I'm quite confident that my fix in #68 is correct, I changed style 1 in this PR consistently. @dirtydancing Anything else that's odd (except your point 4 above which should be fixed in a subsequent PR)? Imo everything's consistent and in place now, isn't it?

So if #68 is merged I think, this one is ready to merge as well

**Comment by dirtydancing** [comment]
As to the colours in style 1: imo the colour e.g. in open-recent should be darker, not lighter, because that one is in the background, not in front.

E.g., when using red `#ff0000`, I get this (incorrect):

recent_ff0000

whereas with "red" I get this (correct):

recent_red

Is this a design decision that can be changed (then I would recommend to adjust) or is this not possible/manageable when having 1 colour exclusively?

**Comment by dirtydancing** [comment]
Has something changed with the folders? I am running in to difficulties when trying to change the individual folder colour via Folder Color in style 5: blue, grey, pink and red are not working.

**Comment by dirtydancing** [comment]
I am inquiring into this last problem. I figure this might be a problem on my side from former testing with previous script versions.

**Comment by wa4557** [comment]
Yeah this seems to be the design decision (lighter background instead of darker background; because this is what @Foggalong did for most of the icons in #6) so it seems that this is the wanted behaviour.

**Comment by dirtydancing** [comment]
Well, that is another inconsistency then, as the predefined colours are having darker colours in the background. This is a detail, but it is strange nevertheless.

**Comment by wa4557** [comment]
Yeah but I think the predefined colours were wrong as well. That's the reason why I created a second pull-request that changed that #69

**Comment by dirtydancing** [comment]
Ah, ok. I figure as long as this is consistent, this should be fine. imo this should still all be darker for those icons instead of lighter, and in other folder styles this is indeed darker, but I guess to each style its own :)

**Comment by dirtydancing** [comment]
Yep, the other problem that just came up with certain folder colours not working for individual folders via Folder Color was a problem on my side, not a problem with the script. Sorry for that.

The possibilities that this custom default colour option offers are fantastic! This can not only address the open issue https://github.com/numixproject/numix-folders/issues/7, as you already mentioned, but also the open issue https://github.com/numixproject/numix-folders/issues/16, at least from the default colour side. Quick example, which could be refined, this is just to demonstrate:

pink:
pink

custom with the "symbol pink" from the Readme as secondary colour:
custom

btw, I am testing all of this with the icon themes installed locally as user. Could there be any difference when having the icon themes installed globally as root and when accordingly running the script as root?

**Comment by wa4557** [comment]
No, works globally as root as well.

**Comment by dirtydancing** [comment]
I thought so, just wondering. I will test as root as well, now that I am through with my testing as user.

**Comment by dirtydancing** [comment]
Something appears to be wrong with in style 1 in `48x48/actions` with

`custom-add-folders-to-archive.svg`
`custom-document-open.svg`
`custom-document-open-recent.svg`

In size `48x48`, these look different from the other sizes, apparently with a fixed blue from colour "blue".

Screenshot with different sizes:
style1

Screenshot of `48x48/actions`:
style1_48x48

**Comment by dirtydancing** [comment]
**2)** Question/suggestion: As I understand it, if a wrong hex colour value is entered for any of the colours, only at the end of all changeable colours a warning will appear to choose a proper colour value and then the process will abort.

Is it possible/reasonable to modify this in a way that this warning/abort appears right after a wrong colour value is entered? That way, if a user unintentionally misspells s.th. in the first colour, there will be no need to fill in the other colours as well, only to be told that s.th. was wrong. Also, it would be clear which entry was wrong. Might be useful even more if folder styles are added with even more than 3 different colours.

**Comment by dirtydancing** [comment]
**3)** Suggestion: Add to the Readme below "custom" a link/links to "colour website/s" that e.g. offer the opportunity to pick colours and display the colour hex value.

This might also be an opportunity to include a link to Numix Croma: croma.numixproject.org/

E.g., to experiment with a secondary colour for style 5, I had a look at the monochromatic palette in Croma and ended up with these colours:

croma1

croma2

**Comment by dirtydancing** [comment]
So far for this testing round. This is great work, thanks! :+1: Using as root is working very smoothly, also the automatic cache update works just fine (which is not part of this custom colour PR, just mentioning it).

**Comment by dirtydancing** [comment]
Even better now! :) 1) is fixed, and as to 3) I figure any further info can also be added later via a separate PR, if needed.

One detail concerning 2): This is working great now after each colour. But I think that the wording can be improved. Right now it reads e.g.:

`Oops! The colour: f990fv is not a valid hex value`
`Try again using six digit values!`

While I liked that the entered colour value was cited, I was irritated by two things: first, "try again", which I thought was somewhat inappropriate, and second the emphasis on "six" digit values, as six digits (and not e.g. an abbreviated 3 digits) had been entered, which I thought was somewhat unclear. I liked the message before: `Be sure to use valid hex values with six digits (e.g. 000000)`

So I would recommend the following, also to stay consistent with the other messages for style and folder, which use the word "invalid", and "invalid" is clearer to quickly read than "not valid" (Oops! You've chosen an invalid style number.
Run 'numix-folders --styles' for an option list):

`Oops! The colour: f990fv is an invalid hex value.`
`Be sure to use valid hex values with six digits (e.g. 000000)`

The timeout when "running in terminal" is long enough for that, cf. https://github.com/numixproject/numix-folders/issues/54 (I checked). What do you make of this?

In addition, a small spelling detail in line 12 of the script (comment):
It should not read
`# Allows timeout when launched vai 'Run in Terminal'` (vai obviously is supposed to read via)
but rather
`# Allows timeout when launched via 'Run in Terminal'`

**Comment by dirtydancing** [comment]
Sweet! My verdict: Ready to go :+1:

What an announcement it will be if this gets merged! And now, glad to be back on style 5 default colour :)

**Comment by dirtydancing** [comment]
@wa4557 Seeing this pull request https://github.com/numixproject/numix-folders/pull/71 by @GLolol about typo fixes in the script, I think there should be periods added at the end of the lines for the messages for the custom colours as well (@GLolol is right):

Oops! The colour: f990fv is an invalid hex value**.**
Be sure to use valid hex values with six digits (e.g. 000000)**.**

**Comment by Foggalong** [comment]
@wa4557 @dirtydancing I'm gonna clone this branch and test this feature. Thanks to both of you for working hard on this :)

**Comment by Foggalong** [comment]
All seems to be working seemlessly for me! :D

**Pull request merged**
