### PR TITLE
add gtk & notify version check

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**

### CODE REVIEW

**Comment by dirtydancing** [comment]
Confirmed that there are no warnings with this version anymore :+1: 

@bil-elmoussaoui Is there a reason why your fork is from @wa4557 and not from numixproject?

**Comment by bil-elmoussaoui** [comment]
@dirtydancing i forked @wa4557 to fix an issue with gui and i forgot to delete and refork numixproject again :P

**Comment by dirtydancing** [comment]
Ah ok, was just wondering. I guess that this should not cause any merging problems.

**Comment by Foggalong** [comment]
It took me way too long to work out that this was a different file :P

**Comment by Foggalong** [comment]
@dirtydancing will the error file require this check also?

**Comment by bil-elmoussaoui** [comment]
@Foggalong yes but only the gtk version check

**Comment by Foggalong** [comment]
:+1:

**Comment by dirtydancing** [comment]
Argh, now the warning when opening is back, but the two warning when running are gone:

```
sys:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
```

**Comment by dirtydancing** [comment]
Just putting in a link to the issue to keep track https://github.com/numixproject/numix-folders/issues/121

**Comment by dirtydancing** [comment]
I just checked again, and apparently, I made a mistake at my end: all is running without any warnings. Sorry for causing potential confusion.

**Comment by dirtydancing** [comment]
Ah, I guess there were now no warnings anymore because of the latest https://github.com/numixproject/numix-folders/commit/10dcafde7c92705893e0de1dff22f16cbd8d664b

**Pull request merged**
