### PR TITLE
Fixes bugs from #47

### LINKED ISSUE #47: Include numix-folders in the Numix PPA
Question: Would it be manageable and reasonable to include the numix-folders package in the Numix PPA? Reasons:

1) This way, there would be no need for users to check back here on GitHub for updates.

2) numix-folders is supposed to be located in the same directory as Numix base anyways.

3) And additionally, this would give some more exposure to the awesome Numix Folders project :)

### PR DESCRIPTION
**Pull request by wa4557**
See #47 my last comment

### CODE REVIEW

**Comment by dirtydancing** [comment]
@Foggalong Is there a fix-related reason why this has not been merged so far? To maybe clarify in case of confusion: This has been tested to fix issue **5** from over at https://github.com/numixproject/numix-folders/issues/47, cf. my comment https://github.com/numixproject/numix-folders/issues/47#issuecomment-113886650.

**Comment by Foggalong** [comment]
@dirtydancing Thanks for reminding me! I was basically wondering whether it's nessisary to have both `-f` and `--remove-destination` as it seem to me that the latter encompasses the former

**Comment by wa4557** [comment]
[You're probably right] (http://unix.stackexchange.com/questions/178235/how-is-cp-f-different-from-cp-remove-destination)

**Comment by wa4557** [comment]
Hmm I'm wondering if there's a better idea than `--remove-destination`. It seems to me that cp does not overwrite the file by default if the source and destination files are the exactly the same. This seems to be reasonable since there are a lot of files :( Anyone has a better idea?

**Comment by Foggalong** [comment]
That's not a bad idea :) I'll get on that this afternoon :)

**Comment by wa4557** [comment]
@Foggalong Are you going to do this? I can as well if you want (it's not a big change after all :). I'll close this here

**Comment by Foggalong** [comment]
I have some icons ready, I've just not commited them yet :)

**Pull request closed without merging**
