### PR TITLE
Fixes #23 and #25

### LINKED ISSUE #23: Inconsistent icon for document-open and for document-open-recent
In Styles No. 2 and  No. 4 and possibly also in Style No. 6, the icon for document-open and for document-open-recent is inconsistent.

In Styles No. 1, 3 and 5, for these two icons in `.../actions`, the same (consistent) icon is used as for fileopen in `.../places`.

But in Styles No. 2 and No. 4, the same icon is used as for folder-open in `.../places`. Yet, document-open refers to opening a document and not to opening an entire folder, so this is potentially misleading:

Style No. 2 `48x48/actions`

2_actions

Style No. 2, `48x48/places`

2_places

Style No. 4, `48x48/actions`

4_actions

Style No. 4, `48x48/places`

4_places

In Style No. 6, also not the same icon as for fileopen is used, but here this is also not the very same icon as for folder-open (that one incluces an arrow pointing upwards), so this could be intentional:

Style No. 6, `48x48/actions`

6_actions

Style No. 6, `48x48/places`

6_places

In contrast, Styles No. 1, 3 and 5 are using the same (consistent) icon for document-open (and document-open-recent) in `.../actions` as for fileopen in `.../places`.

Style No. 1

1_actions

Style No. 3

3_actions

Style No. 5

5_actions

Well, since this a kind of a tie (3 to 3), this all could be intentional after all :-) Still reporting it, because to me the document-open (actions) and fileopen (places) icon is a consistent combination.

### PR DESCRIPTION
**Pull request by wa4557**
Fixes #23 and #25 can't be split, so one pull request

### CODE REVIEW

**Comment by Foggalong** [comment]
I know it's been a while with no news on this on, but rest assured I'm getting around to it. With it being a bit more complex than the average pull I want to wait till I've properly got time to sit down with it :)

**Comment by wa4557** [comment]
Hey, no worries :)  I don't mind actually. I just like to fix bugs. If you merge, great if not fine as well :)

**Comment by Foggalong** [comment]
I've spoke with @me4oslav and we would be happy to merge this commit! :D
There's a small issue though - this change affects 2 icons (`default-document-open.svg` & `default-document-open-recent.svg`) in 3 of the styles, each across 9 sizes & 10 colors. But then `2 × 3 × 9 × 10 = 540` and this merge is only affecting 539 files meaning 1 has been missed off :(

**Comment by wa4557** [comment]
Oh my. I'll try to find the missing icon

**Comment by wa4557** [comment]
Hmm is it possible that one of the icons was changed later to the correct one? 
`git diff --name-only 728dac46e7bbb1111d52fd9a35315a1dfb802b0b 220de5c4f7887c2ef45124e1d0803cc9017fc4d5` shows me 540 icons

**Comment by Foggalong** [comment]
That's really odd! I guess it's possible if it accidentally slipped into another commit - we haven't changed anything on our side though so couldn't have happened with you? I guess it being a GitHub error is alsona possibility

**Comment by wa4557** [comment]
Ok. I'll try rebasing a little bit and trying some other git magic. Give me a few moments

**Comment by wa4557** [comment]
Ok I have absolutely no idea what's going on here... I'm not able to do this. Can I send you the files, and you do it?

**Comment by wa4557** [comment]
Ok This is most probably a github bug. Merging this PR really should and will change 540 files

**Pull request closed without merging**
