### PR TITLE
Fixes qt opacity issue

### PR DESCRIPTION
**Pull request by wa4557**
I fixed the icons where Qt was not able to display them properly. @palob Can you check if everything is ok now?

Needs to be copied to the main numix repo to close numixproject/numix-icon-theme#1001

### CODE REVIEW

**Comment by palob** [comment]
Looks like everything is fixed except for the ``...add-folders-to-archive`` action icons for style **4**.

The style **5** ``...add-folders-to-archive`` action icons have got slightly misplaced paths.
style4

**Comment by wa4557** [comment]
Thanks. I cannot reproduce the style 4 issue though. That should be fixed actually

**Comment by palob** [comment]
Style 5 issue is fixed :+1: 

This is how  ``default-add-folders-to-archive.svg`` looks in Nomacs 3.0 (Qt 5.7.0)
default-add-nomacs

This is the Dolphin 16.04.3 preview:
add-folders-dolphin

**Comment by wa4557** [comment]
Alright. I fixed the last remaining issues with style 4. From my point of view it can be merged...

**Comment by palob** [comment]
Everything fine now :+1:  Thanks for your efforts.

**Comment by Foggalong** [comment]
This is awesome! Thanks for the fix :D

**Pull request merged**
