### PR TITLE
Adds small preview icons for gui

### LINKED ISSUE #118: Dropdown Preview Icons
This is just an enhancement the the existing GUI which was constructed for #102. The idea is to add little preview icons next to the options in the dropdown so that options are presented in a more user friendly manor. This would be similar to how [Folder Color does](http://2.bp.blogspot.com/-tblqIpef9RE/VHiMOmhXnhI/AAAAAAAAU8g/ExdKvg_0xdE/s1600/linuxmint171cajafoldercolor.png) it's colour choosing menu. There's a bit more discussion on that topic [here](https://github.com/numixproject/numix-folders/issues/102#issuecomment-134619273)

### PR DESCRIPTION
**Pull request by wa4557**
That was actually pretty hard to do, but I finally figured out that works. This fixes #118

### CODE REVIEW

**Comment by Foggalong** [comment]
While I love this, it isn't quite what I meant. My idea was to have previews of the folder with default colour in the style dropdown and preview of the primary colour in the colour dropdown. Maybe this is better though? Thoughts from people appreciated

**Comment by wa4557** [comment]
Yeah Ok I misunderstood that... But I actually think this is better, because you really see what's going on if you change something. 

If you want I could add preview pictures for the colour though, but which one exactly? (Primary maybe?)

**Comment by Foggalong** [comment]
Yeah, primary colour preview would be good :D 

No problem with the shoutout, I had completely missed that

**Comment by wa4557** [comment]
Easy :) Should I then keep the style preview the way it is, or change that to the default colours, which doesn't change when changing the colour?

**Comment by Foggalong** [comment]
Yeah, that'd be good :)

**Comment by wa4557** [comment]
Now it should be the way you want it:)

**Comment by Foggalong** [comment]
I'm suddenly really unsure of which looks better. Sorry about this, today is my first day out of hospital after yet another accident so I'm still a bit woozy :(

**Comment by wa4557** [comment]
Maybe a hybrid then? The style preview from before but keep the colour preview rectangles (that would be my prefered way to do it)

Yeah riding the bike is dangerous I speak from experience :P

**Comment by Foggalong** [comment]
Yeah, I'm happy to go with that :) haha, yeah!

**Comment by wa4557** [comment]
Ok, done

**Comment by Foggalong** [comment]
Great! As ever, thanks for your amazing work on this :)

**Comment by dirtydancing** [comment]
This is fantastic! :+1: (all folder style preview colours are changing according to the chosen colours, and the primary colour rectangles are displayed for the colour selection)

**Pull request merged**
