### PR TITLE
Fixed #44

### LINKED ISSUE #44: Folder naming for "Projects" is inconsistent
The folder names for "Projects" are `projects` in sizes 16x16, 48x48 and 96x96, but in contrast `project` for the other sizes.

This issue report is just to keep track: the issue is already being addressed in https://github.com/numixproject/numix-folders/pull/43.

### PR DESCRIPTION
**Pull request by figgyc**
I hope this works. Replaces https://github.com/numixproject/numix-folders/pull/43

### CODE REVIEW

**Comment by wa4557** [comment]
Looks good :)

**Comment by figgyc** [comment]
I won't.

**Comment by dirtydancing** [comment]
@figgyc Haha, no I think you are looking good as well here :) I can tell you, I have been looking very closely at this folder ocean consisting of thousands and thousands of folder files, and I have not caught the "projects" naming inconsistency.

**Comment by dirtydancing** [comment]
Confirmed that I could not find any more "project"-named folder files either: looking good indeed :)

**Comment by dirtydancing** [comment]
And the good thing about these folders being named `projects` is that those icons in size `16x16` that are only present in Numix base and not in Numix-Folders do not need to be renamed, because they are already correctly named `projects` :), cf. https://github.com/numixproject/numix-folders/issues/26

**Comment by dirtydancing** [comment]
@figgyc To let you know: I came across another naming inconsistency, for "Google Drive" :), cf. https://github.com/numixproject/numix-folders/issues/48.

**Pull request merged**
