### PR TITLE
Consistency to "projects" folders as agreed in https://github.com/numixproject/numix-icon-theme/pull/456"

### PR DESCRIPTION
**Pull request by figgyc**
See https://github.com/numixproject/numix-icon-theme/pull/456

### CODE REVIEW

**Comment by dirtydancing** [comment]
Great! I believe this would now need to be done consistently for all 6 folder styles :-)

**Comment by figgyc** [comment]
Okay. Is there a way to add to this pull or will I need to make another?

**Comment by wa4557** [comment]
Two things: All 6 styles would be great + you didn't move you copied therefore the old *folder-project.svg are still there

**Comment by wa4557** [comment]
you can add to your pull request if you just push the changes to your fork

**Comment by figgyc** [comment]
@wa4557 doing the rest of the folder styles now. Are you sure that the old ones are still there? I don't see them in my local tree

**Comment by dirtydancing** [comment]
I just created a corresponding issue report, just to keep track, cf. https://github.com/numixproject/numix-folders/issues/44.

**Comment by wa4557** [comment]
@figgyc yes https://github.com/figgyc/numix-folders/blob/master/files/6/Numix/64x64/places/blue-folder-project.svg

**Comment by figgyc** [comment]
Right my new commit will fix that when I push, and do all six folderstyles

**Comment by wa4557** [comment]
Sorry but they are still there:) Just run something like `find . -iname "*folder-project.svg" -exec rm {} \;`

**Comment by figgyc** [comment]
Right. Will do

**Comment by figgyc** [comment]
Wait whoops i deleted the wrong files! Hang on I'll do a revert.

**Comment by wa4557** [comment]
No you didn't everything seems to be fine now :)

**Comment by figgyc** [comment]
Oh yeah sorry I just keep forgetting what name we want. Let me go and fix it

**Comment by figgyc** [comment]
Is it all right? I think I may have accidentally screwed up with git.

**Comment by wa4557** [comment]
No you didn't push :)

**Comment by figgyc** [comment]
Wait all my projects files are gone on local side aswell. Is there a way to quickly get back to the last good commit?

**Comment by figgyc** [comment]
Right so I just need to push and all is well? That's good

**Comment by wa4557** [comment]
I have no idea what's happening on your computer locally. You could try `git checkout master` delete the files and add the commit once more

**Comment by figgyc** [comment]
```
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
```

I think I need to somehow revert to the numixproject's repository and then reapply the patch from there?

**Comment by figgyc** [comment]
Okay all is well except I need to delete the files again.

**Comment by wa4557** [comment]
`git remote add upstream https://github.com/numixproject/numix-folders`
`git fetch upstream`
`git checkout master`
`git reset --hard upstream/master`
`git push origin master --force `

and start over

**Comment by figgyc** [comment]
It just autoclosed, shall I recommit?

**Comment by wa4557** [comment]
Yeah recommit! And create a new pull request

**Comment by figgyc** [comment]
Right okay.

**Comment by dirtydancing** [comment]
@figgyc I just checked your last master-branch from above, and indeed, and I can confirm that there were still incorrectly named `project` files in there :-)

For a new pull request, it might make sense to use a branch off your master.

**Pull request closed without merging**
