### PR TITLE
Added numix-folders.svg icon

### PR DESCRIPTION
**Pull request by dirtydancing**
Addresses one aspect of https://github.com/numixproject/numix-folders/issues/102, cf. https://github.com/numixproject/numix-folders/issues/102#issuecomment-128749834. Placed in the new folder `icons`.

numix-folders

### CODE REVIEW

**Comment by wa4557** [comment]
Great, although I don't think the icon should be placed where you put it. I guess it's better to put in it in the packaging branch together with a desktop file? (I could be wrong, never packaged anything)

**Comment by dirtydancing** [comment]
@wa4557 Probably you are right, I do not know.

@PaoloRotolo As you know about packaging: Any suggestions from your side?

**Comment by Foggalong** [comment]
@dirtydancing now that the repo has a bit more bulk (the GUI) it's possible we should rethink how we deal with storing the packaging. I'm not 100% on the icon either - it has to be a design which will translate into all the different styles too

**Comment by dirtydancing** [comment]
No worries about the design, please feel free to close this PR and the corresponding PR over at Numix-Circle, https://github.com/numixproject/numix-icon-theme-circle/pull/2474. I pushed these so that the icons would not get lost.

As to the design translating to the different styles: style 1 as a baseline seemed fine to me, because it is the "classic" Numix style and it has a wide area to place the colours on (scales just fine).

I see two possible difficulties with translating into all the different folder styles:

1) Changing with the folder style would probalby limit the design choices, as they have to fit on all styles. And it would have to be distinct enough from the default colours to avoid confusion.

2) Possibly relating to the packaging: if this generic icon will be placed in `hicolor` rather than in Numix base, I am not sure if changing it would be a problem when running the script (?).

Then again, I cannot really say anything relating to the packaging.

**Comment by Foggalong** [comment]
I think I've had an idea about the icon so don't worry too much about it. I'll leave this pull open to remind me :)

**Comment by dirtydancing** [comment]
OK :)

**Comment by dirtydancing** [comment]
Just seeing that you added icons for Circle and Square for the different styles - looking very good! :+1:

**Comment by wa4557** [comment]
But there still needs to be a generic icon for numix-folders in `hicolor` if the user wants to use it without circle or square

**Comment by Foggalong** [comment]
Yeah, not added that yet because I'm not 100% sure where it should be added

**Comment by Foggalong** [comment]
I've just had a thought though - what icon is shown in docs when the GUI is opened?

**Comment by wa4557** [comment]
`application-default-icon` But that's just because I didn't specify an icon (can be done via pygtk)

**Comment by Foggalong** [comment]
Does that icon specification fetch it from hicolor?

**Comment by wa4557** [comment]
Not necesarily. As far as I understand I can assign a theme icon (with the whole lookup procedure) So it could be put in base `numix` as well. 

I think however that this is not a good idea, because if a user uses another icon theme, but still has numix-folders installed no icon will show up

**Comment by Foggalong** [comment]
So we should include it in the packaging and then just copy it to `/hicolor`?

**Comment by wa4557** [comment]
I think (and I'm by no means an expert in packaging things) the way it is done is to add a folder `/usr/share/icons/hicolor/48/apps` with the `numix-folders` icon in it to the packaging branch, and copy it to the computer while installing. 

The thing is however: simple cloning and running the script doesn't work then anymore and a makefile etc. will be necessary

**Comment by Foggalong** [comment]
Yeah, that just occurred to me. Maybe with the GUI integrated in now and the restore from backup option, now is the time to switch to a makefile?

(CC: @PaoloRotolo @satya164 @me4oslav)

**Comment by dirtydancing** [comment]
To confirm: after https://github.com/numixproject/numix-folders/pull/108, the "Gui" icon is showing e.g. in the dash with Arch/GNOME (numix-folders GUI started from the command line) :+1: 

Screnshots with Numix-Circle and with Numix (with proposed icon from above placed in `hicolor`):

numix-circle

numix

**Pull request closed without merging**
