### PR TITLE
Add script for macOS

### PR DESCRIPTION
**Pull request by BKrajancic**
I have been using the icon pack on macOS, and wanted to contribute my script that I use for conversion to .icn

### CODE REVIEW

**Comment by Foggalong** [comment]
Since this isn't a macOS version of the project but a script for exporting the assets I'm not gonna merge it into the main repo. I have [added it to the wiki](https://github.com/numixproject/numix-folders/wiki/macOS-Usage) though because I think it's cool when people  remix our use our work in ways we weren't expecting like this! I'll still be merging this PR so that you get proper commit credit but I've modified it to reflect that. 

Out of curiosity, have you used [Numix Core's](https://github.com/numixproject/numix-core) macOS export feature? We know it works in theory but very few of the Numix team actually use it to test rigorously.

**Comment by BKrajancic** [comment]
Yes I have, based on https://github.com/numixproject/numix-core/pull/5622#event-4591993392 it looks like my compatibility suggestions have been merged in.

It appears that MacOS big sur has broken the software I usually use for setting icons, so i've not got around to setting all the numix icons manually recently. The script in the repo was working fine though, last I checked.

**Comment by Foggalong** [comment]
This is what I get for working through PRs reverse chronologically :joy: Sad to hear that the compatibility for icons generally isn't working great atm, but glad to hear the Numix software is generally working well!

**Comment by BKrajancic** [comment]
So, turns out the compatibility still works with apps, but not built in apps. So I can get stuff like vscode working but not system settings. Thought it may be worth mentioning cause i've set them up again

**Comment by Foggalong** [comment]
Thanks for the update Benjamin!

**Pull request merged**
