### PR TITLE
Adds command line flag to use previously stored settings

### PR DESCRIPTION
**Pull request by wa4557**
Before I push a nice gui (which is finished now btw \o/) another necessary thing for that. A config file where the previous settings are stored and can be retrieved by using `-p` on the command line without asking the user for any input

### CODE REVIEW

**Comment by wa4557** [comment]
Btw: this kind of deals with #101, and the flag could be used as a postinstall routine when updating numix or numix-circle

**Comment by Foggalong** [comment]
As far as I can tell it's impossible to introduce the script into the post install routine. There are just too many variables that we don't have control over such as whether the folder script is installed, how the user installed it, where they installed it to, how they have other icon themes installed, etc

**Comment by wa4557** [comment]
Fair enough, still this is definitely a usefull addition :)

**Comment by Foggalong** [comment]
Aye!

**Comment by wa4557** [comment]
I'm sorry I have to close this and add a new one with the gui already included. Those two features are too closely related to be separated in distinct pull-requests...

**Comment by Foggalong** [comment]
Fair enough! Sorry for not having the time to get to this sooner :(

**Pull request closed without merging**
