### PR TITLE
Runs inkscape --vacuum-defs on all files

### PR DESCRIPTION
**Pull request by wa4557**
Since no other PR are open right now, I thought it might be a good idea to clean up the existing icons, bu running `inkscape --vacuum-defs` on all icons. For most of the icons nothing changed but the filename in the svg :)

### CODE REVIEW

**Comment by palob** [comment]
Just a small thing: You've actually made the Circle icons bigger as they already had been processed using the ``svgclean`` script which is more rigorous :)

**Comment by wa4557** [comment]
Hmm I thought I didn't touch the circle square icons, exactly because of that (at least they are not altered in the tree of this PR)

**Comment by wa4557** [comment]
Yeah circle and square icons were not altered by this PR :)

**Comment by palob** [comment]
:+1:

**Pull request merged**
