### PR TITLE
Adds default option for styles entry

### PR DESCRIPTION
**Pull request by wa4557**
Asterisk for default option in GUI

### CODE REVIEW

**Comment by dirtydancing** [comment]
Looking very good :+1:

Screenshot with Arch/GNOME/default Adwaita GTK above and Numix GTK below (the colour selection box has moved a bit to the right now that the style selection box is a little wider, which is just fine):

default

numix

One thing though: I am not sure if the large preview icon at the top is totally centered, could be ever so slightly off to the left?

@bil-elmoussaoui Could you check and confirm that all is fine at your end?

**Comment by bil-elmoussaoui** [comment]
Works fine here too :+1: 
screenshot from 2016-01-03 22-36-58
Btw, i will be away for two/three weeks! Finals are coming..

**Comment by dirtydancing** [comment]
Sweet! And good luck! So I figure this is ready to be merged then :+1:

**Comment by wa4557** [comment]
It's actually not so straightforward to center an element in Gtk (you have to do it by eye basically) but I think in this case it is as centered as possible :-)

**Comment by dirtydancing** [comment]
@wa4557 Thanks for the info about Gtk, I was not aware of that.

**Pull request merged**
