### PR TITLE
Remove double return

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
Some devs consider having more than one return in a function is bad programming :P

### CODE REVIEW

**Comment by satya164** [comment]
Seriously?

**Comment by bil-elmoussaoui** [comment]
Yes, almost every teacher that i had said that

**Comment by satya164** [comment]
Hearing this for the first time!

**Comment by wa4557** [comment]
I disagree. This makes the code more complicated and is therefore not "good" practice. The aversion against things like multiple returns, break and continue is something I never understood.
See also: 
https://stackoverflow.com/questions/36707/should-a-function-have-only-one-return-statement

**Comment by bil-elmoussaoui** [comment]
In this case it does really make the code complicated. And i ever understood the thing about "break" neither!

**Comment by satya164** [comment]
@bil-elmoussaoui yeah

**Comment by Foggalong** [comment]
Yeah, agreed. Looking at those posts it seems like it's a historical reason rather than any current aesthetic or functional reason.

**Pull request closed without merging**
