### PR TITLE
Adjusted colours spelling in Readme to the default colour switcher script

### PR DESCRIPTION
**Pull request by dirtydancing**
Fixes https://github.com/numixproject/numix-folders/issues/52.

Screenshot:

colours_spelling

### CODE REVIEW

**Comment by cisoun** [comment]
I don't think it is really necessary to do that. Someone or I (when I'll have a moment) could simply add a code in the script to transform in lowercase the color entered by the user. That will avoid the script to look for wrong file names and the user to care about the letter case.

**Comment by dirtydancing** [comment]
Agreed that it would be even better if the user can enter uppercase or lowercase :)

Still I think that the Readme should correspond to the "default" spelling. E.g., I entered lowercase anyways, so I think that there still is an argument for lowercase also in the Readme.

One more idea (without opening yet another issue at this point): would it also be possible for the colour (and maybe at the same time also for the style) to just hit the return key to get the default, i.e. without specifically having to type "default"?

**Comment by cisoun** [comment]
Certainly. I'll keep this idea for later unless someone implements it.

**Comment by dirtydancing** [comment]
Great, thanks!

**Comment by Foggalong** [comment]
I do actually quite like this. Going to merge it because it keeps it consistent with the style section, but I'll put in the lower case converter too.

**Pull request merged**
