### PR TITLE
Graphical user interface with using previously stored settings

### PR DESCRIPTION
**Pull request by wa4557**
As laid ut in my previous PR here is the PR with a GUI and also an option to reuse previously stored settings. I think I have tested and fixed almost every possible scenario, and it works pretty great :)

### CODE REVIEW

**Comment by wa4557** [comment]
One thing that is probably not yet ideal, where hopefully someone could help:
So far I'm using `gksudo` when the icon theme is installed globally and elevated privileges are necessary. According to (this) [http://askubuntu.com/questions/284306/why-is-gksu-no-longer-installed-by-default] however `gksudo` is obsolete and not platform independent. 
The question remains: what should I use instead, given the fact that I need a graphical sudo?

**Comment by Foggalong** [comment]
I think you're okay using `gtksudo` for now. `pkexec` is what I've heard is going to be the replacement for it but as far as I know it isn't really at a stage where it can be easily deployed right now

**Comment by palob** [comment]
At least for Fedora there is ```beesu``.

**Comment by wa4557** [comment]
But that's exactly the problem: ON different distros there are different ways to launch a graphical sudo. I guess I could implement that for each of the major distros, but that would mean a lot of (unnecessary) cluttered code...

**Comment by Foggalong** [comment]
Yeah, just stick with gksudo. Until a clear alternative replaces it it's just not feasible to adjust it on a per platform basis :/

**Comment by wa4557** [comment]
A big improvement: instead of copying/reading and writing the preview icons each time user selects something different from the GUI. The svg is now stored in a pixbuf variable and the colour in the svg-string is now converted on the fly

**Comment by Foggalong** [comment]
I've still not had time to look this over, but noticed [this commit](https://github.com/wa4557/numix-folders/commit/2d25132a0bb3c56a5051caab3ffd740332241a38). Thanks you <3

**Comment by wa4557** [comment]
Haha, I thought you'd like it. The gtk functions are still AE though :P

**Comment by wa4557** [comment]
@Foggalong Is it too much to ask to revert your last commit and look at this PR beforehand and add the `-r` flags afterwards? I guess I could solve the conflicts but I'd rather not

**Comment by Foggalong** [comment]
Yeah, that's totally fine. I'll revert my commit ASAP.

**Comment by Foggalong** [comment]
Reverted \O/

**Comment by wa4557** [comment]
Thanks. I could add this here if you want

**Comment by Foggalong** [comment]
Nah, that's alright. Gonna test the GUI stuff now :D

**Comment by Foggalong** [comment]
First impression - they way the GUI is implemented so that you use the folder style & a colour option as a base for custom colours is brilliant. Really really great!

**Comment by Foggalong** [comment]
Just ran the script can got this output (though the change was successfully made)

```bash
Folder change complete!

(gui:31556): Gtk-WARNING **: Theme parsing error: gtk.css:2337:33: Missing name of pseudo-class

(gui:31556): Gtk-WARNING **: Theme parsing error: gtk.css:2341:33: Missing name of pseudo-class
Traceback (most recent call last):
  File "./gui/notification", line 7, in <module>
    n.show()
GLib.Error: g-io-error-quark: Could not connect: Connection refused (39)
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
```

**Comment by bil-elmoussaoui** [comment]
@wa4557 Notify seems to not be working on all the distro..

**Comment by bil-elmoussaoui** [comment]
@Foggalong can you try changing the notification file code to this 
`
#!/usr/bin/python3

from gi.repository import Notify
from subprocess import Popen
try:
  Notify.init("numix-folders")
  n = Notify.Notification.new("Numix-folders", "applying...", "gtk-info")
  n.show()
except:
  Popen(['notify-send',"Applying.."])
` 
and try again

**Comment by Foggalong** [comment]
Done! Output now reduced to this

```bash
Folder change complete!

(gui:3854): Gtk-WARNING **: Theme parsing error: gtk.css:2337:33: Missing name of pseudo-class

(gui:3854): Gtk-WARNING **: Theme parsing error: gtk.css:2341:33: Missing name of pseudo-class
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
```

**Comment by bil-elmoussaoui** [comment]
Gtk3 handles desktop notifications now, but it's seems not working on your distro, so i modified to code to use `notify-send` if there's a problem sending the GTK3 notification
One question, you've received any notification?

**Comment by Foggalong** [comment]
No notification on my end :( My setup is i3/compton/xfce but the notifications come through `xfce4-notifyd`

**Comment by bil-elmoussaoui** [comment]
Implementing a notification system that will work with all the distro will be really hard :/  the only solution that we can do is to use [Pynotify](http://home.gna.org/py-notify/) Which works with almost all the distro's but the user will need to install `sudo apt-get install python3-pyinotify` 
documentation [here](http://seb.dbzteam.org/pyinotify/)

**Comment by Foggalong** [comment]
Yeah, adding more dependencies is a bit poo. XFCE is a pretty standard DE to work with though, and I'm yet to run into another app which has worked with GNOME (for e.g.) and not it.

**Comment by wa4557** [comment]
Yeah the notification was more like a gimmick, bceause @dirtydancing suggested it, it is absolutely not necessary, and if it doesn't show, meh...
But yeah from an official GTK implementation one would suspect a bit more universality...

**Comment by bil-elmoussaoui** [comment]
I suggest to keep the notification file, one day all the distro's will support it ;)

**Comment by Foggalong** [comment]
Yeah, I kinda understood their concerns though. The closing of the window is a bit abrupt. Rather than having OK/Cancel maybe it would be better to just have an apply button? Then the window stays open and it's not so bad if the notification isn't supported by the DE. Also make subsequent testing of different themes a bit slicker too

**Comment by wa4557** [comment]
I tried that, but I coudn't come up with an easy idea to let the python script know that the bash script is finished

**Comment by Foggalong** [comment]
hmmm. not sure what the solution would be there then :/

**Comment by bil-elmoussaoui** [comment]
@wa4557 just one question , is the gui file is just an interface or it's used to execute the bash script?

**Comment by wa4557** [comment]
just an interface. The work is done in the bash script

**Comment by wa4557** [comment]
Well one thing I could do: replace the OK button with an apply button, and after the button is clicked the gui stays open for a few seconds, regardless of success. What you think?

**Comment by dirtydancing** [comment]
Just for the record :) : I did not suggest a separate notification, but rather the GUI displaying s.th. like "applying", cf. https://github.com/numixproject/numix-folders/issues/102#issuecomment-128317350. Too bad that this is not possible.

@Foggalong Initially, the notification was not showing with Arch/GNOME either. But after I installed the Arch package `notify-osd` it showed up, cf. screenshot over at https://github.com/numixproject/numix-folders/issues/102#issuecomment-128514285. For what it is worth.

@wa4557 I agree with @bil-elmoussaoui that keeping the notification is just fine, as the worst case scenario apparently is that the notification will simply not show.

In addition, I think that having the button read "Apply" instead of "OK" is a good idea. I am not so sure about having the GUI stay open for a fixed time, though. Having the GUI just stay might be irritating if the changes actually show up right away (the time neede seems to differ), and if the GUI does not close, this might mislead the users to think that they did not press the button, so they might be prompted to press it again. Once the user presses "Apply", it should be quite clear that the changes are being applied :)

**Comment by wa4557** [comment]
Ok, that's not doable anyways. Another thing I could do: Try if the notification works and if not open a gtkdialog that shows the same message...

**Comment by bil-elmoussaoui** [comment]
@wa4557 the best solution!

**Comment by wa4557** [comment]
Ok I added an applying message after pressing apply on the gui, if the notification doesn't work. @dirtydancing: Is this the way you imagined it to be?

**Comment by dirtydancing** [comment]
Question for clarification: e.g. with Arch/GNOME, with the `notify-osd` package installed, I get the notification "bubble", just like mentioned before. Without that package, I now get this new "dialog":

applying

Do I understand correctly that the changes are only applied when I click "OK"? If that is the case, then I would say this is more confusing than before. Just clicking "Apply" in the GUI seems better to me.

Or does this new dialog go away automatically once the changes are applied? I have waited quite a while, but so far the new "Applying" dialog has not gone away, and changes were not applied without clicking "OK".

**Comment by wa4557** [comment]
@dirtydancing Yeah this should work now

**Comment by dirtydancing** [comment]
Relating to `Detaches notification dialog`: now the changes are applied right away. But I still have to press "OK" in order for the "Applying" dialog to close. Is it possible to have this dialog close automatically, if not possible in accordance with the change, then possibly after a fixed time?

**Comment by wa4557** [comment]
Not anymore, try again :)

**Comment by dirtydancing** [comment]
Haha, I will :) Anyways, another good thing that I noticed: when running from the command line, no error/warning messages are showing up.

**Comment by wa4557** [comment]
:+1: Do you still want the "OK" button in the notification dialog or do you think I should remove it altogether?

**Comment by dirtydancing** [comment]
Checking the latest https://github.com/wa4557/numix-folders/commit/a8a83ca419011e4c2cb1415a3d773a63e7248d67: As the "Applying..." dialog now auto-closes after 3 seconds, I think it is better to leave the "OK" removed, as it already is. Given the restrictions discussed above, I really like this newest variant :+1: 

One more thing: now the "Applying..." is marked. Is it possible to have this unmarked, like before?

Detail: And is it possible to have the text vertically centered? Currently, it is situated somewhat low.

Screenshot:

applying_new

**Comment by wa4557** [comment]
Ok, I'm working on the marked text, I think I can solve this problem as well. 
Regarding vertical centering: That's because you're using a gtk-theme without title bars, if you're using Ambiance or Numix the text is centered :)

**Comment by dirtydancing** [comment]
Yeah, this is what the window looks like with Numix GTK theme, so I figure vertical positioning is just fine:

numix-gtk

**Comment by wa4557** [comment]
If you want to try again, it should work now :)

**Comment by dirtydancing** [comment]
Confirmed that the text "Applying..." is unmarked now :+1:

**Comment by dirtydancing** [comment]
And by the way, I also really like that the last used custom colour shows up when opening the GUI, and it is possible to keep the very same custom colour while changing the folder styles.

**Comment by bil-elmoussaoui** [comment]
I tried the script in elementary, and i see both the notification & the dialog notification 
screenshot from 2015-08-19 11 40 14

**Comment by bil-elmoussaoui** [comment]
And i don't know anything about this message in the terminal too 
`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.`

**Comment by dirtydancing** [comment]
Interesting. With Arch/GNOME, either the notification bubble or the notification dialog is showing up, but not both.

And with Arch/GNOME, I do not get the `Gtk-Message` from above.

**Comment by wa4557** [comment]
The error message is related to the gtk theme, not my fault. But why are both showing up? try except should handle that...

**Comment by wa4557** [comment]
@bil-elmoussaoui Can you comment out the except part of the script and only try the `try` part in the terminal, and tell me what the error message is

**Comment by bil-elmoussaoui** [comment]
This what i've got 
```
Traceback (most recent call last):
  File "./gui/notification", line 24, in <module>
    n.show()
gi._glib.GError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.Notifications' on object at path /org/freedesktop/Notifications
```

**Comment by wa4557** [comment]
But the notification is still showing oO?

**Comment by dirtydancing** [comment]
I just checked with Arch/GNOME for both notification variants and with several GTK themes (Adwaita, Numix, Ozon, Evopop, Arc), and I never got any messages/warnings/errors on the command line.

**Comment by bil-elmoussaoui** [comment]
@wa4557 I figured it out, this error message has nothing to do with the notification see [here](https://developer.gnome.org/notification-spec/) 
Changing the code to that worked for me; 
```
#!/usr/bin/python3

from gi.repository import Notify, Gtk, GLib

message = "Applying..."

def dialog_destroy(widget):
    widget.destroy()
    return True

class NotificationDialog:
    def __init__(self):
        self.dialog = Gtk.MessageDialog(None, None,Gtk.MessageType.INFO, Gtk.ButtonsType.NONE, message)
        label = Gtk.Entry()
        self.dialog.set_focus(label)
        GLib.timeout_add(3000, dialog_destroy, self.dialog)
        self.dialog.run()
        self.dialog.destroy()

if __name__ == "__main__":
    Notify.init("numix-folders")
    n = Notify.Notification.new("Numix-folders", message, "gtk-info")
    if n:
        try:
            n.set_urgency(1)
            n.show()
        except:
            pass   
    else:   
        dialog = NotificationDialog()    
``` 
@dirtydancing  can you change the code in `gui/notification` to that and see if everything works fine?

**Comment by wa4557** [comment]
@bil-elmoussaoui This is code is somehow dangerous. Does it work if the `notify.init` and `n = ` part is also in the `try` section?

**Comment by bil-elmoussaoui** [comment]
@wa4557 Won't work :/ I don't know if we can implement something like this 
```
try:
   from gi.repository import Notify
 except: 
     use_dialog = True
.... 
```

**Comment by wa4557** [comment]
Sure we can impolement something like this, but the import works on elementary too doesn't it?

**Comment by dirtydancing** [comment]
I can come back to this later on.

**Comment by bil-elmoussaoui** [comment]
@wa4557 Yes :/ The problem is that the notification server is somehow not working and the try/except part thought that was an error and that's why the dialog message is shown

**Comment by wa4557** [comment]
But it is working, obviously...

**Comment by wa4557** [comment]
Ok, I tried to come up with a solution but couldn't think of anything. I would argue that the best solution is to just live with the fact that both notifications are shown. With this I guess I'm finished!? (Unless someone has other bugs)

**Comment by Foggalong** [comment]
Maybe we could just remove the notification and just have the pop up?

**Comment by dirtydancing** [comment]
Is this problem of two parallel notifications only showing in elementary OS? Is it a bug in elementary?

I take it then that I am not supposed to do any testing on this with Arch/GNOME?

Just asking the obvious here: How about just having the "Applying..." dialog notification and not the bubble notification at all? This would work universally for all distros, wouldn't it? Am I missing s.th. here?

**Comment by dirtydancing** [comment]
Haha @Foggalong, are we asking the same question at the same time? :)

**Comment by Foggalong** [comment]
Also in @bil-elmoussaoui's screenshot above everything looks a bit lopsided? Is that normal?

**Comment by dirtydancing** [comment]
I have also been wondering where the "i" graphic element in the dialog window in the screenshot of @bil-elmoussaoui form above is coming from. As you can see in my screenshots from above, with Arch/GNOME there is only the "Applying..." text in the window.

**Comment by wa4557** [comment]
Of course I can remove the notification (although it is arguable the better choice if it works), should I do that?

**Comment by bil-elmoussaoui** [comment]
@Foggalong, @dirtydancing  I have no idea, i used the same version as you

**Comment by Foggalong** [comment]
@wa4557 thought was that if the popup is always going to show up anyway then it may as well be the only method?

**Comment by wa4557** [comment]
It seems that this only happens for @bil-elmoussaoui in elementary. For me (and @dirtydancing ) only the notifications shows

**Comment by bil-elmoussaoui** [comment]
Its might be a bug in elementary :/ But we didn't try the script in every distro. I would suggest to just use the show the popup using GTKdialog

**Comment by dirtydancing** [comment]
Yeah, that is what I meant earlier: why not have the GTK dialog popup (3 seconds) as the only "notification", and do without the "notification bubble" via `notify-osd` altogether?

**Comment by wa4557** [comment]
I still think that the "benefit" of keeping the notifications is bigger than the "disadvantages" of removing it. But if you all vote for removing I'll remove it

**Comment by dirtydancing** [comment]
What is the benefit of the notification versus the gtk dialog popup in your opinion?

**Comment by wa4557** [comment]
well because a notification just notifies me without occuping the whole screen whereas the popup looks worse, and is not a notification per se

**Comment by dirtydancing** [comment]
Understood. Still, with the latest spin you gave the popup (auto-closing after 3 seconds), to me it fulfills its purpose just fine and comes close enough to a "proper" notification.

This being said, I can see why you would prefer a "proper" notification, and as I am not sure why this is showing double in elementary OS (bug?), I would also be happy with it :)

**Comment by dirtydancing** [comment]
Just checked the latest version with Xubuntu 15.04 (VM): all fine, ootb only the notification is showing, not additionally the gtk popup. Also no messages/warnings/errors via the command line. :+1:

**Comment by bil-elmoussaoui** [comment]
I think its might be an elementary issue, I will report that there. Just keep only the notification as the issue is only in eOS ;)

**Comment by bil-elmoussaoui** [comment]
Done. See [here](https://bugs.launchpad.net/elementaryos/+bug/1486734)

**Comment by dirtydancing** [comment]
Ah, with Arch/GNOME I checked again the GUI version via command line (not the command line with the `-t` flag), and I also got the other message that has come up before, with default Adwaita GTK theme:

`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.`

**Comment by wa4557** [comment]
Just ignore that, that's harmless

**Comment by dirtydancing** [comment]
OK :)

**Comment by Foggalong** [comment]
@dirtydancing @wa4557 @bil-elmoussaoui ready to merge then? :D

**Comment by bil-elmoussaoui** [comment]
yes, elementary devs confirmed that its a bug with Gala 😀

**Comment by dirtydancing** [comment]
Yes, agreed, ready to merge :+1:

**Comment by wa4557** [comment]
Go ahead :+1:

**Comment by Foggalong** [comment]
Merged! I won't be announcing it on the Numix page until it's had a bit of testing and all the relevant icons have been added to their respective themes :)

**Comment by wa4557** [comment]
Cool, I guess there has to be a proper .desktop file somewhere in the packaging branch (together with the icon), but I have no idea where exactly :)

**Comment by bil-elmoussaoui** [comment]
the script  should be called while updating too ;)

**Comment by Foggalong** [comment]
@bil-elmoussaoui as mentioned previously, that can't be reliably done

**Comment by dirtydancing** [comment]
Question: Am I missing s.th. here? I cloned via git and copied `numix-folders` into `usr/share/icons`. When running `sudo ./numix-folders` I get the following, but the change is applied successfully:

```
sudo ./numix-folders
touch: „/home/root/.config/numix-folders“ kann nicht berührt werden: Datei oder Verzeichnis nicht gefunden
sed: kann /home/root/.config/numix-folders nicht lesen: Datei oder Verzeichnis nicht gefunden
sed: kann /home/root/.config/numix-folders nicht lesen: Datei oder Verzeichnis nicht gefunden
sed: kann /home/root/.config/numix-folders nicht lesen: Datei oder Verzeichnis nicht gefunden
sed: kann /home/root/.config/numix-folders nicht lesen: Datei oder Verzeichnis nicht gefunden
sed: kann /home/root/.config/numix-folders nicht lesen: Datei oder Verzeichnis nicht gefunden
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
Folder change complete!
./numix-folders: Zeile 314: /home/root/.config/numix-folders: Datei oder Verzeichnis nicht gefunden
./numix-folders: Zeile 315: /home/root/.config/numix-folders: Datei oder Verzeichnis nicht gefunden
./numix-folders: Zeile 316: /home/root/.config/numix-folders: Datei oder Verzeichnis nicht gefunden
./numix-folders: Zeile 317: /home/root/.config/numix-folders: Datei oder Verzeichnis nicht gefunden
./numix-folders: Zeile 318: /home/root/.config/numix-folders: Datei oder Verzeichnis nicht gefunden
chown: Zugriff auf „/home/root/.config/numix-folders“ nicht möglich: Datei oder Verzeichnis nicht gefunden
```

Also, apparently the last setting was not saved.

In contrast, when copying `numix-folders` to a local user directory and running `sudo ./numix-folders`, all is running find and I only get the aforementioned:

`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.` 

So is there a requirement to "install" (place) `numix-folders` in a local user directory?

**Comment by wa4557** [comment]
Hmm strange. I'm not an expert on this. 
@Foggalong Shouldn't `cuser="${SUDO_USER:-$USER}"` ensure that always the local user is selected?

**Comment by wa4557** [comment]
not reproducible on my end...

**Comment by dirtydancing** [comment]
Yeah, I guess this was a mistake from my side. I just checked again, and I figured that I was already running the terminal as root, so `sudo` was not really necessary :) Running `./numix-folders` went just fine, and only when adding `sudo` and running `sudo ./numix-folders` the above messages appeared.

**Pull request merged**
