### PR TITLE
Max length for colours entry

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
Before
screenshot from 2015-12-20 00-54-40
After
screenshot from 2015-12-20 00-59-05
I added a bonus : The Application is on the center of the screen by default

### CODE REVIEW

**Comment by wa4557** [comment]
Great, was trying this for a long time. Is it possible to reduce the spacing between colour buttons and entries?

**Comment by bil-elmoussaoui** [comment]
Yes, i will do that as soon as i can ;)

**Comment by bil-elmoussaoui** [comment]
Like this? 
screenshot from 2015-12-20 12-05-01

**Comment by palob** [comment]
Maybe put the *Cancel* button into the lower left corner?
Would make the GUI look more centered and you won't hit the wrong button inadvertently.

**Comment by bil-elmoussaoui** [comment]
Like this? 
screenshot from 2015-12-20 12-39-09

**Comment by palob** [comment]
:+1:

**Comment by bil-elmoussaoui** [comment]
It's not perfectly aligned.. 
screenshot from 2015-12-20 12-47-29

**Comment by palob** [comment]
Looks still better than before imo. How does it look when the margin between the styles and colour button is as narrow as before?

**Comment by bil-elmoussaoui** [comment]
Looks better! :+1: 
screenshot from 2015-12-20 12-58-26

**Comment by bil-elmoussaoui** [comment]
I think that the Cancel button shouldn't be used at all... as the settings are not applied automatically; but only when you click on the apply button

**Comment by palob** [comment]
So only Apply centered?

**Comment by bil-elmoussaoui** [comment]
Apply centered 
screenshot from 2015-12-20 13-03-33

In the right corner 
screenshot from 2015-12-20 13-02-42


I think the best thing is to keep it on the right corner and add the apply button style

**Comment by palob** [comment]
Like for instance white letters on blue for Adwaita?

**Comment by wa4557** [comment]
What if you left align the colourbuttons and the entries. The centering doesn't look right imo...

**Comment by palob** [comment]
Hmm yeah, full width for the colour text fields might look better.

**Comment by bil-elmoussaoui** [comment]
The full width is not really a good idea... Maybe adding a label for primary/secondary colour ?

**Comment by wa4557** [comment]
I still think that a cancel button is necessary. That's actually good design practice...

**Comment by bil-elmoussaoui** [comment]
I didn't remove it from the patch, do you know how to get the default css file using Gtk ? so we can apply it to the buttons? :P  The GTK documentation is really poor :/

**Comment by wa4557** [comment]
What you mean by default css?

**Comment by bil-elmoussaoui** [comment]
Well you can use Gtk.CssProvider to load a css file; what i want is to load the default css style (in the current theme) or a way to apply the Apply/Cancel style's

**Comment by wa4557** [comment]
Ah ok, no idea. Gtk coding is really a pain in the ass...

**Comment by bil-elmoussaoui** [comment]
Still waiting for a better integration btw Glade & Builder!

**Comment by wa4557** [comment]
What if you label the three entries? That would fill up the length...

**Comment by bil-elmoussaoui** [comment]
Something like this? 
screenshot from 2015-12-20 14-49-33

**Comment by wa4557** [comment]
Not sure. I think it's slightly better. I would make the distance between the GtkEntry and the GtkColourButton even smaller

**Comment by wa4557** [comment]
Btw: the dropdown menus are not centered...

**Comment by bil-elmoussaoui** [comment]
screenshot from 2015-12-20 15-00-14
What should we show as labels? :)

**Comment by wa4557** [comment]
Maybe something like Primary Colour, secondary colour and icon colour?

**Comment by bil-elmoussaoui** [comment]
Looks so nice! :+1: 
screenshot from 2015-12-20 17-34-50

**Comment by wa4557** [comment]
Align it to the right side and use ":"?

**Comment by bil-elmoussaoui** [comment]
Aligned the preview and added ":"
screenshot from 2015-12-20 17-40-21
You mean aligning the labels to the right or the colour entry's ?

**Comment by palob** [comment]
Does *Cancel* close the app?

**Comment by wa4557** [comment]
Aligning the labels to the right (not to the left as it is now) would be better I guess

**Comment by wa4557** [comment]
Yes cancel closes the app

**Comment by palob** [comment]
Isn't a *Reset* button more useful then?

**Comment by wa4557** [comment]
Well that's what the "Default" item in the dropdown is used for

**Comment by bil-elmoussaoui** [comment]
@wa4557 I will need to modify few lines of code..
I just used few margins to use the empty space btw the colours entries 
screenshot from 2015-12-20 17-49-20

**Comment by bil-elmoussaoui** [comment]
The final result :  
screenshot from 2015-12-20 19-45-27

I moved also the application from a normal Widget to an ApplicationWidget, I just need to look more in the GTK documentation on how to fix this #132.

**Comment by wa4557** [comment]
Still thin that the labels should be aligned to the right side... Otherwise it looks better

**Comment by bil-elmoussaoui** [comment]
I'm still thinking of the easiest way to do that , so lazy :P

**Comment by wa4557** [comment]
Isn't it just a `label.set_alignment(1,0)`?

**Comment by bil-elmoussaoui** [comment]
Nop not working :/

**Comment by bil-elmoussaoui** [comment]
Found it :P 
screenshot from 2015-12-20 20-24-25

**Comment by wa4557** [comment]
Way better!

**Comment by palob** [comment]
A wider *Apply* button?

**Comment by bil-elmoussaoui** [comment]
@palob I'm still trying to figure out how to use default CSS classes in GTK;

**Comment by bil-elmoussaoui** [comment]
@wa4557 I had to move `Gtk.Buttons` to `Gtk.Builder` so i can use `suggested-action` css class
screenshot from 2015-12-20 20-53-57

**Comment by palob** [comment]
Way to go :+1: but doesn't raise it the GTK dependency (which was 3.0 before IIRC)?
I've rejected my headerbar idea for that reason.

**Comment by bil-elmoussaoui** [comment]
I didn't,  Gtk.Builder is just reading the `xml` code that in `.ui` files saved using Glade and converting them to Gtk Objects; 
I fixed some alignements and pushed the code ;) 
screenshot from 2015-12-20 21-08-14

**Comment by wa4557** [comment]
Erm, why is my apply button now green? (using Numix GTK theme) (And the preview is not aligned)
bildschirmfoto vom 2015-12-20 21-12-34

**Comment by palob** [comment]
The colour is due to the GTK theme.

**Comment by wa4557** [comment]
I haven't seen a bit of green anywhere else...

**Comment by palob** [comment]
What's your distro?

**Comment by bil-elmoussaoui** [comment]
In Arc theme everything looks fine ;) it's a Numix theme issue. 
screenshot from 2015-12-20 21-18-07

**Comment by wa4557** [comment]
Ubuntu 15.10

**Comment by bil-elmoussaoui** [comment]
Can you verify if the preview is aligned now? I used the Css class used in almost every application for buttons.. I can remove it if you want to ;) 
screenshot from 2015-12-20 21-20-46

**Comment by wa4557** [comment]
Preview is aligned. No keep it I think it's the best way to do it :)

**Comment by palob** [comment]
I know Ubuntu patches their GTK stack and uses outdated versions, maybe they've set it up not to show coloured buttons?
What is more those buttons usually appear in headerbars which still arent in Ubuntu AFAIK.

**Comment by wa4557** [comment]
It really seems to be a Numix GTK theme issue, with Arc everything looks fine...

**Comment by palob** [comment]
It's not an issue I think, it's a feature. You can define that colour in the theme.

**Comment by bil-elmoussaoui** [comment]
I have never seen that green before neither..

**Comment by wa4557** [comment]
Yeah sure, I think it's just weirdly chosen in Numix.

**Comment by dirtydancing** [comment]
Hey guys, phantastic stuff going on here. Here is a screenshot comparison with Arch/GNOME and default Adwaita GTK theme.

Current:

current

Proposed:

proposed

I really like the proposed version! :+1: 

I am just wondering:

1. Are the boxes supposed to be right-aligned on the right side? Because they do not look quite on the same line at the right-side edge. And using different GTK themes, esp. the colour box in the upper right moves somewhat horizontally, sometimes the right edge is located a little to the left of the three colour values, other times even a little more to the right.

2. To me, the "Secondary Colour:" looks a little odd as the "S" appears to be further to the left hand edge than the style box above. It is not, but it makes that optical impression. To me, the left-alignment of the text (which has been discussed above) looks better. Alternatively, to not have "Secondary Colour:" be so long, and because "Colour" imo is not really needed here: maybe keep the right-alignment of the texts and name those three texts just "Primary:", "Secondary:" and "Icon:" (without "Colour")?

**Comment by bil-elmoussaoui** [comment]
@dirtydancing  I don't know how we can really align them perfectly. @wa4557 Maybe using a fixed grid? 
I was setting a margin from left/right to align them; but this will not look great on lower screen resolution or other themes..

What do you guys think about this result ? I removed almost every margin from the code, and i think that we should not perfectly align them :P 
screenshot from 2015-12-23 00-45-45

**Comment by palob** [comment]
Maybe no colon and tighter text-colour button spacing like in the lowermodt example in [this section of the GNOME HIG](https://developer.gnome.org/hig/stable/visual-layout.html.en)?

**Comment by dirtydancing** [comment]
Sweet :+1: imo not aligning perfectly (just as currently) is a very good way to go, as things start to look odd when there is just an "almost" perfect alignment.

And I like the labels without the "Colour" part. I like both of the latest variants posted, and personally I maybe prefer the second one with the labels left-aligned.

**Comment by dirtydancing** [comment]
Haha, I knew this one is a close call :) Having another look at the two latest variants, I now prefer the first one with the right-aligned labels. The "S" of "Secondary" does not look out of place anymore, the readability is better when the ":" all have the same distance from the colour boxes, and the focus is on the colour boxes as it should be. This composition of boxes and labels looks very efficient and elegant.

**Comment by bil-elmoussaoui** [comment]
@Palob i will see what i can do this evening
And do you think that we should keep the "Numix Folders GUI" as a title ? Maybe without "GUI"

**Comment by wa4557** [comment]
First one is definitely better. As @palob suggested let's to what is specified in the GNOME HIG. So no colon right aligned, 12px between label and entry. 6px spacing between lines and 18px margin on each side. GNOME is usally really good concerning this sort of things :)

**Comment by dirtydancing** [comment]
Agreed, I have just checked out the link that @palob provided, and that to me looks very good indeed.

**Comment by wa4557** [comment]
@bil-elmoussaoui Yeah drop the GUI

**Comment by bil-elmoussaoui** [comment]
What do you think? I removed every margin left/right from the source code, tried to make the space btw text- colour buttons as mentioned in Gnome HIG. 
screenshot from 2015-12-23 23-22-39

**Comment by wa4557** [comment]
Remove the colons as well (":"). I also think that there needs to be a little bit more space between the main GUI and the buttons

**Comment by palob** [comment]
Yeah, more space above *Cancel* *Apply*.

**Comment by bil-elmoussaoui** [comment]
Done :+1: 
screenshot from 2015-12-23 23-33-14

**Comment by dirtydancing** [comment]
The space above "Apply" could be even a little bigger, like before imo.

Is there a way to center the boxes with the colour preview in them? Before they looked centered just like the big preview icon above, but now without the colons they look "almost" centered, which is odd imo.

**Comment by wa4557** [comment]
Yeah even more space + I would also move them more to the right, such that the spacing is the some to the bottom top and the right...

**Comment by bil-elmoussaoui** [comment]
Aligned to right
screenshot from 2015-12-24 00-01-14
Or something like this? 
screenshot from 2015-12-24 00-02-28

**Comment by wa4557** [comment]
I think the last one is close to perfect :+1:

**Comment by bil-elmoussaoui** [comment]
Pushed the latest version :+1: 
@wa4557 @palob @dirtydancing Can you guys try it , as everyone is using a different distro, different GTK theme..So we can test it and see if it's ready to be merged. Thanks!

**Comment by palob** [comment]
:+1: Looks alright with Adwaita, Arc, breeze-gtk, elementary, evopop, greybird, paper GTK themes.

**Comment by dirtydancing** [comment]
With default Adwaita GTK theme:

new

Are you sure you pushed the last one? Because in this screenshot of mine, we are back to the problem that it looks "almost" right-aligned, which is odd imo.

Furthermore, now the "Apply" button looks even more to the right, which is odd imo.

Also, again the colour preview boxes look "almost" centered, which is odd as well imo.

What a tricky GUI :)

**Comment by dirtydancing** [comment]
Just an idea: how about abbreviating "Primary" as "1ry" and "Secondary" as "2ry"? These abbreviations appear to exist, and that way, the center part with the three colours might be moved more flexibly?

**Comment by wa4557** [comment]
For me it looks somehow crooked. 
bildschirmfoto 2015-12-24 09 49 57

**Comment by bil-elmoussaoui** [comment]
I forgot to change a value in the code, should look like that now
screenshot from 2015-12-24 11-56-31

**Comment by dirtydancing** [comment]
Looking good in Arch/GNOME with default Adwaita GTK theme (and also with Arc, Evopop, HighContrast, Numix, Numix-Frost, Ozon, Paper GTK themes) :+1:

Screenshot with default Adwaita GTK theme:

proposed_new

Screenshot with Numix GTK theme:

proposed_new_numix_gtk

**Comment by Foggalong** [comment]
Veto the 1ry abbreviations. While I've seen them before they're rare enough that it'll confuse a good proportion of users.

**Comment by bil-elmoussaoui** [comment]
@Foggalong  :+1:

**Comment by dirtydancing** [comment]
Yeah, agreed :) The latest version looks very good with "Primary" and "Secondary", screenshots above.

**Comment by Foggalong** [comment]
Yeah, you 4 have done a brilliant job here refining the interface. Really looking gorgeous :heart:

**Comment by wa4557** [comment]
@bil-elmoussaoui Can you add the `StartupWMClass` to the desktop file as well? As far as I understand this should fix the blurry icon, and since the correct icon name is no also showing in the launcher, I think the GUI is finally at a point where it hardly can be improved :)

**Comment by bil-elmoussaoui** [comment]
@wa4557 Done; Once this PR is merged we will see what we can do later to fix other issues

**Comment by dirtydancing** [comment]
Agreed that this PR is ready to be merged, I just opened the current GUI, and this one is so much improved indeed :+1: Screenshot of the current one and the new one next to each other (Adwaita GTK):

gui_current_new

Actually, I noticed one more inconsistency: The colour texts should read Primary, Secondary and **Symbol**, not Icon. "Symbol" is also used via Terminal, and "Icon" is confusing because it relates to the entire folder icon, not specifically to the third symbol colour.

**Comment by bil-elmoussaoui** [comment]
Yeah! i'm going to change the icon to symbol! :+1:

**Comment by bil-elmoussaoui** [comment]
@dirtydancing Done

**Comment by dirtydancing** [comment]
Brilliant! :dancers:

symbol

**Comment by dirtydancing** [comment]
All working great with Arch/GNOME, except the icon is still blurry with ALT + TAB. I will open a new issue.

**Pull request merged**
