### PR TITLE
Use default colors in other styles

### PR DESCRIPTION
**Pull request by wa4557**
As requested here's the pull request. I tried to make it as futureproof as possible :)

### CODE REVIEW

**Comment by Foggalong** [comment]
This is what happened when I picked `style: 5`, `colour: style2`. Because 5 works fine for custom colours I'm guessing this is a problem with the new code. 

screenshot_2015-05-17_15-23-56

**Comment by wa4557** [comment]
Yeah but this is not my fault, because style 2 only has primary colour and symbol colour (for me the symbols show up) so it's inherentely impossible to use style 5 with colours from style 2 and get a colour for the secondary colour -> the default colour from style 5 is used

**Comment by wa4557** [comment]
As for style 2: Ok Does this mean, that the outline colour should be listed as secondary colour? If so I can do that

**Comment by Foggalong** [comment]
Similar problem with picking and style and using style 1s colours.
screenshot_2015-05-17_15-29-20

From what I can tell, these are the changes that need to be made:

* style 2 custom needs to be modified so that the outline colour is listed as the secondary colour and the symbol listed as the symbol colour (even though they remain the same for all the default icons)

* style2 colour then needs to use both col2def and col3def (even though they point to the same colour) so that it can successfully be used with other themes

* style 1 did have a secondary colour designed for it unintentionally (see #68, fixed in #69). Use that colour as the default secondary colour and then `#f9f9f9` as the default symbol colour. That means that style 1 can still be used with the higher sizes :)

**Comment by wa4557** [comment]
Will do. Will take a little while I have to think of a clever way to bash that :)

**Comment by Foggalong** [comment]
Aye, no problem. It's a lot of changes to be expected to do manually

**Comment by wa4557** [comment]
Should be fixed now. As an sideeffect the it was possible to clean the code a little bit because of these changes :)

**Comment by Foggalong** [comment]
Choosing `style: 2; colour: style1` gave me this 
screenshot_2015-05-17_16-58-21
Possibly a misplaced hexcode somewhere?

**Comment by wa4557** [comment]
Yeah I used blue instead of default

**Comment by Foggalong** [comment]
ahhh :P

**Comment by Foggalong** [comment]
All looks good to me! Great job :D

**Comment by wa4557** [comment]
Thanks :)

**Pull request merged**
