### PR TITLE
Add wine-winefile icons

### PR DESCRIPTION
**Pull request by mymindstorm**
The icons should be fine except for perfect grid alignment on the X axis because I kept the symbol proportional. 

Is there something like `data.json` that I need to edit here to get them to work correctly?

### CODE REVIEW

**Comment by mymindstorm** [comment]
Sorry for the blurriness, Gnome's file manager doesn't like to scale things properly.
image

**Comment by mymindstorm** [comment]
@palob @Foggalong since there hasn't been an update in a week on this I was wondering if I need to do anything, if nobody had the time for this yet, or if  this just got forgotten

**Comment by Foggalong** [comment]
@mymindstorm I'll be honest, I just never saw the notification! Pinned this so it'll be the next review I do :)

**Comment by mymindstorm** [comment]
Thanks!

**Comment by mymindstorm** [comment]
I don't see what's wrong with it, the shadow on the folder is already 1px down and to the right? 
image

Also, when I was double checking the other style 5 icons I noticed that some of them used 2px between the symbol and left side of the folder while other icons used 3px

image
image

Is there a size I should be using here?

**Comment by palob** [comment]
@Foggalong was referring to the symbols on top of the folders. As a matter of fact however it's that way (just 1px down) for all the other icons, be it on purpose or by mistake.

**Comment by Foggalong** [comment]
@palob oh shit is it really? I have no idea whether or not that is intentional and the answer is likely lost in the logs of the old Numix IRC channel where we used to do development. I'm gonna go with it being unintentional, but I'll merge this one now and then we can fix the rest at a later date

**Pull request merged**
